version: '3'

services:
  find-a-friend-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=findafriend
      - POSTGRESQL_PASSWORD=petfriend
      - POSTGRESQL_DATABASE=findafriend
